/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.inicio;

/**
 *
 * @author luis
 */
public class ventanaInicio extends objetos.objetoVentana {

    public ventanaInicio(Boolean html, String posicionRelativa) {
        super(html, posicionRelativa);
        ajustar();
    }

    private void ajustar() {
        clase = "paginaPrincipal";
        primeraParte = ""
                + "<section data-section-title='primeraSeccion'class='primeraSeccion panel' id = 'primeraSeccion'>\n"
                + "     <div>\n"
                + "         <div class='imagenFondo'>\n"
                + "              <div class='imagen'>&nbsp;</div>\n"
                + "              <div class='blur'>\n"
                + "                   <div>\n"
                + "                      <h1>MediCall</h1>\n"
                + "                      <h3>Cuidando a tu salud </h3>\n"
                + "                    </div>\n"
                + "              </div>\n"
                + "         </div>\n"
                + "         <div class='imagenOla'>&nbsp;</div>\n"
                + "      </div>\n"
                + "</section>";
        segundaParte = ""
                + "<section data-section-title='segundaSeccion' class='segundaSeccion panel' id = 'segundaSeccion' data-section-name = 'segundaSeccion'>\n"
                + "   <div>\n"
                + "       <div class='derecho'>\n"
                + "            <div class='pequeño'>\n"
                + "                 <div class='imagen'>\n"
                + "                      <div></div>\n"
                + "                 </div>\n"
                + "                 <div class='titulo'>\n"
                + "                        ¿Qué es MediCall?\n"
                + "                 </div>\n"
                + "                        <div class='texto'>\n"
                + "                                      <br>"
                + "                                    Seas doctor o paciente, buscamos siempre tu beneficio. Doctores a la puerta de tu casa, dispuestos a ofrecerte"
                + "                                    el mejor de los servicios sin salir de tu hogar ni perder tiempo en traslados o tediosas citas. \n"
                + "                                      <br>"
                + "                                    Pruébalo. Crea tu cuenta en 4 sencillos pasos para facilitar tu vida y la de tus familiares con la nueva manera de estar sano... de estar bien.  \n"
                + "                                </div>\n"
                + "                                <div class='extra'>\n"
                + "                                      <br>"
                + "                                    <label>\n"
                + "                                        Conoce más acerca de 'Familia '\n"
                + "                                    </label>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                            <div class='grande'>\n"
                + "                                <div class='imagen'>\n"
                + "                                    <div></div>\n"
                + "                                </div>\n"
                + "                                <div class='titulo'>\n"
                + "                                   Conecta, personaliza y disfruta...\n"
                + "                                </div>\n"
                + "                                <div class='texto'>\n"
                + "                                      <br>"
                + "                                    El muindo de la tecnología, además de crecer exponencialmente también te envuelve y es por ello que rescatamos la facilidad del desarrolllo de proyectos de software. "
                + "                                        pues no olvides que eres nuestra prioridad como cliente. \n"
                + "                                </div>\n"
                + "                                      <br>"
                + "                                <div class='extra'>\n"
                + "                                    <div class='azulado'>\n"
                + "                                        <label>\n"
                + "                                            Ver más\n"
                + "                                        </label>\n"
                + "                                    </div>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                        <div class='izquierdo'>\n"
                + "                            <div class='grande'>\n"
                + "                                <div class='imagen'>\n"
                + "                                    <div></div>\n"
                + "                                </div>\n"
                + "                                <div class='titulo'>\n"
                + "                                    Pruébala\n"
                + "                                </div>\n"
                + "                                <div class='texto'>\n"
                + "                                      <br>"
                + "                                    Prueba la forma más creativa, eficiente y atractiva de recibir atención médica. \n"
                + "                                    Es tu derecho.  \n"
                + "                                    Sientete cómoda estando en tu casa y sé feliz sabiendo que beneficias también a la otra pesona.\n"
                + "                                </div>\n"
                + "                                      <br>"
                + "                                <div class='extra'>\n"
                + "                                    <div class='rojoso'>\n"
                + "                                        <label>\n"
                + "                                            Ver más\n"
                + "                                        </label>\n"
                + "                                    </div>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                            <div class='pequeño'>\n"
                + "                                <div class='imagen'>\n"
                + "                                    <div></div>\n"
                + "                                </div>\n"
                + "                                <div class='titulo'>\n"
                + "                                    Descarga la App \n"
                + "                                </div>\n"
                + "                                <div class='texto'>\n"
                + "                                      <br>"
                + "                                    Ahora, no solo podrás disfrutar de los beneficios de MediCall en Web\n"
                + "                                    llevamos a tu celular el servicio médico que te mereces y lo hacemos más fácil. ¡Descárgala! \n"
                + "                                </div>\n <br>"
                + "                                <div class='extra'>\n"
                + "                                    <label>\n"
                + "                                        Acerca de... \n"
                + "                                    </label>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                </section>";
        terceraParte = ""
                + "<section data-section-title='terceraSeccion' class='terceraSeccion panel' id = 'terceraSeccion'>\n"
                + "                    <div class='divContenedor'>\n"
                + "                        <div class='titulo'>\n"
                + "                            <h3>¡Súmate!</h3>\n"
                + "                            <label>\n"
                + "                                Tú también puedes ser parte de este gran proyecto.\n"
                + "                            </label>\n"
                + "                        </div>\n"
                + "                        <div class='contenedor'>\n"
                + "                            <div>\n"
                + "                                <div class=' miniContenedor'>\n"
                + "                                    <div class='otroDiv'>\n"
                + "                                        <div class='imagen'>\n"
                + "                                            <diV class='circulo rojoso'>a</diV>\n"
                + "                                        </div>\n"
                + "                                        <div class='textoContenedor'>\n"
                + "                                            <div class='tituloDiv'>Doctor</div>\n"
                + "                                            <div class='textoDiv'>\n"
                + "                                               Si eres doctor y deseas ganar experiencia o trabajar por tu propia cuenta, aquí tienes la oportunidad. Ve a la sección de 'Soy médico' y conoce todos los detalles.  \n"
                + "                                            </div>\n"
                + "                                        </div>\n"
                + "                                    </div>\n"
                + "                                    <div class='otroDiv'>\n"
                + "                                        <div class='imagen'>\n"
                + "                                            <diV class='circulo rojoso'>a</diV>\n"
                + "                                        </div>\n"
                + "                                        <div class='textoContenedor'>\n"
                + "                                            <div class='tituloDiv'>Enfermero</div>\n"
                + "                                            <div class='textoDiv'>\n"
                + "                                                ¡Reconoce tus servicios, también son importantes! Puedes ir a la sección de 'Soy médico' o direcatmente crea tu cuenta y empieza a descubrir el universo de posibilidades que te brinda MediCall\n"
                + "                                            </div>\n"
                + "                                        </div>\n"
                + "                                    </div>\n"
                + "                                    <div class='otroDiv'>\n"
                + "                                        <div class='imagen'>\n"
                + "                                            <diV class='circulo rojoso'>a</diV>\n"
                + "                                        </div>\n"
                + "                                        <div class='textoContenedor'>\n"
                + "                                            <div class='tituloDiv'>Paciente</div>\n"
                + "                                            <div class='textoDiv'>\n"
                + "                                               Ahora puedes evitar todas aquellas molestias que el acudir a una cita o consultorio médico te causa. Si eres mayor de edad y estás listo para descubir nuevas oportunidades, CREA TU CUENTA.  \n"
                + "                                            </div>\n"
                + "                                        </div>\n"
                + "                                    </div>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                </section>";
        cuartaParte = ""
                + "<section data-section-title='pieDePagina' class='pieDePagina panel' id = 'pieDePagina'>\n"
                + "                    <div class='contenido'>\n"
                + "                        <div class='logoEmpresa'>\n"
                + "                            <h3>ILC ®</h3>\n"
                + "                            <div>\n"
                + "                                &nbsp;\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                        <div class='secciones'>\n"
                + "                            <h3>Secciones</h3>\n"
                + "                            <ul>\n"
                + "                                <li>a</li>\n"
                + "                                <li>a</li>\n"
                + "                            </ul>\n"
                + "                        </div>\n"
                + "                        <div class='links'>\n"
                + "                            <h3>&nbsp;</h3>\n"
                + "                            <ul>\n"
                + "                            </ul>\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                </section>";
        quintaParte = "";
        JS = "";
    }

}
