/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.inicio;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author luisjimenezdelgado
 */
public class ventanaFormularioPaciente extends objetos.objetoVentana {

    private String altas = "";

    public ventanaFormularioPaciente(Boolean html, String posicionRelativa) {
        super(html, posicionRelativa);
        ajustar();
    }

    private void ajustar() {

        clase = "";
        primeraParte = "<div class='spaceFix'>\n"
                + "                &nbsp;\n"
                + "            </div>"
                + "<form id='msform'  class='formulario' name='formulario' method='POST' action='" + altas + "altas' enctype='multipart/form-data' accept-charset='UTF-8'> \n"
                + "                <div id='barrita'  class='barrita'>\n"
                + "                    <ul class='' id='progressbar'>\n"
                + "                        <!-- progressbar -->\n"
                + "                        <li id='li1' class='active1 active'></li>\n"
                + "                        <li id='li2'></li>\n"
                + "                        <li id='li3'></li>\n"
                + "                        <li id='li4'></li>\n"
                + "                    </ul>\n"
                + "                </div>\n"
                + "                <div id='form'>";
        segundaParte = "<fieldset>\n"
                + "                        <div class='titulo'>\n"
                + "                            Crea tu cuenta\n"
                + "                        </div>\n"
                + "                        <div class='content'>\n"
                + "                            <div class='divAbsoluto'>\n"
                + "                                <label  for='nombre' class=''>Nombre(s):</label>\n"
                + "                                <input type='text' id='nombre' placeholder=\"Nombre\" maxlength=\"50\" name = 'nombre' onkeypress='return soloLetras(event)'/>\n"
                + "                            </div>\n"
                + "                            <div class='divAbsoluto'>\n"
                + "                                <label  for='apellido' class=''>Apellidos:</label>\n"
                + "                                <input type='text' id='apellido' placeholder=\"Apellidos\" maxlength=\"50\" name = 'apellido' onkeypress='return soloLetras(event)'/>\n"
                + "                            </div>\n"
                + "                            <div class='divAbsoluto'>\n"
                + "                                <label  for='email' class=''>Correo:</label>\n"
                + "                                <input type='text' id='email' placeholder=\"Email\" name='email' />\n"
                + "                            </div>\n"
                + "                            <div class='divAbsoluto'>\n"
                + "                                <label for='telefono' class=''>Telefono:</label>\n"
                + "                                <input type='text' id='telefono' placeholder=\"Telefono de 10 digitos\" maxlength=\"10\" onkeypress='return enteros(event)' name='telefono'/>\n"
                + "                            </div>\n"
                + "                            <div class='divAbsoluto'>\n"
                + "                                <label  for ='pass' class=''>Contraseña:</label>\n"
                + "                                <input type='password'  placeholder='Contraseña de mínimo 8 dígitos' maxlength=\"24\" id='pass' name='pass' />\n"
                + "                            </div>\n"
                + "                            <div class='divAbsoluto'>\n"
                + "                                <label for = 'cpass' class=''> Contraseña:</label>\n"
                + "                                <input type='password' placeholder='Repite tu contraseña' id='cpass' name='cpass' />\n"
                + "                            </div>\n"
                + "                            <div  class='foto'>\n"
                + "                                <div class='izquierdo' style=\"height:  100%\">\n"
                + "                                    <div class='arriba'>\n"
                + "                                        <label id='nom'>Nombre</label>\n"
                + "                                        <label>Email</label>\n"
                + "                                    </div>\n"
                + "                                    <div class='abajo'>\n"
                + "                                        <input type='file' name='fotoUsu' id='fotoUsu' onchange='cambiar(this)' accept='image/*'>\n"
                + "                                        <label for ='fotoUsu'> Adjuntar foto</label>\n"
                + "                                    </div>\n"
                + "                                </div>\n"
                + "                                <div class='derecha'>\n"
                + "                                    <div class='fotito' id='fotoUsuario'>\n"
                + "                                        &nbsp;\n"
                + "                                    </div>\n"
                + "                                </div> \n"
                + "                            </div>\n"
                + "                            <div class='divBotones'>\n"
                + "                                <div class='derecha'>\n"
                + "                                    <span class='next rojoso' name='next' onclick='verifica(1)' >\n"
                + "                                        Siguiente\n"
                + "                                    </span>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                    </fieldset>";
        terceraParte = "<fieldset>\n"
                + "                        <div class='titulo'>\n"
                + "                            Información Médica\n"
                + "                        </div>\n"
                + "                        <div class='content'>\n"
                + "                            <div class='divAbsoluto'> \n"
                + "                                <label for='sexo'> Sexo: </label>\n"
                + "                                <label for='sexo'> Masculino </label>\n"
                + "                                <input type='radio' name='sexo' value='1' id='rad1' onclick=''>\n"
                + "                                <label for='sexo'> Femenino </label>\n"
                + "                                <input type='radio' name='sexo' value='0' id='rad2' onclick=''>\n"
                + "                            </div>\n"
                + "                            <div class='divAbsoluto'>\n"
                + "                                <label>Tipo de Sangre:</label>\n"
                + "                                <select style='width: 40%;color:#666' id='sangre' name='sangre'>\n"
                + "                                    <option value='null' selected name='sangre'>Tipo de sangre</option>\n"
                + "                                    <option value='1'>+A</option>\n"
                + "                                    <option value='2'>-A</option>\n"
                + "                                    <option value='3'>+B</option>\n"
                + "                                    <option value='4'>-B</option>\n"
                + "                                    <option value='5'>+O</option>\n"
                + "                                    <option value='6'>-O</option>\n"
                + "                                    <option value='7'>+AB</option>\n"
                + "                                    <option value='8'>-AB</option>\n"
                + "                                </select>\n"
                + "                            </div>\n"
                + "                            <div class='divChico' style='display:none;' >\n"
                + "                                <label  for='edad' class=''>Edad:</label>\n"
                + "                                <input type='text' id='edad' name='edad' onkeypress='return enteros(event)' required  maxlength=\"3\" min=\"1920-01-02\"/>\n"
                + "                            </div>\n"
                + "                            <div class='divChico'>\n"
                + "                                <label  for='fechaNac' class=''>Fecha de Nacimiento:</label>\n"
                + "                                <input type='text' id='fechaNac' name='fechaNac' placeholder = 'dd/mm/yyyy' required  maxlength=\"10\" min=\"1940-01-02\" pattern='^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$'/>\n"
                + "                            </div>\n"
                + "                            <div class='divChico'>\n"
                + "                                <label for='peso' class=''>Peso (en kg):</label>\n"
                + "                                <input type='text' id='peso' name='peso'   placeholder = 'Ej:70' maxlength=\"4\" onkeypress='return enteros(event)' />\n"
                + "                            </div>\n"
                + "                            <div class='divChico'>\n"
                + "                                <label for ='altura' class=''>Altura:</label>\n"
                + "                                <input type='text' id='altura' name='altura'   maxlength=\"4\" placeholder = 'Ej:1.80' onkeypress='return especial(event)'><br>\n"
                + "                            </div>\n"
                + "                            <div class='divTexto'>\n"
                + "                                <label>\n"
                + "                                    En caso de tener alguna alergia,describela aqui:\n"
                + "                                </label>\n"
                + "                                <textarea id='alergias' name='alergias'></textarea>\n"
                + "                            </div>\n"
                + "                            <div class='divBotones'>\n"
                + "                                <div class='izquierda'>\n"
                + "                                    <span class='previous rojoso' name='previous'>\n"
                + "                                        Anterior\n"
                + "                                    </span>\n"
                + "                                </div>\n"
                + "                                <div class='derecha'>\n"
                + "                                    <span class='next azulBotones' name='next' onclick='verifica(2)' >\n"
                + "                                        Siguiente\n"
                + "                                    </span>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                    </fieldset>";
        cuartaParte = " <fieldset>\n"
                + "                        <div class='titulo'>\n"
                + "                            Antecedentes familiares\n"
                + "                        </div>\n"
                + "                        <div class='content' >\n"
                + "                            <div class='divTexto'>\n"
                + "                                <label>\n"
                + "                                    Selecciona tus antecedentes:\n"
                + "                                </label>\n"
                + "                            </div>\n"
                + "                            <div class=\"divCheck\">\n";
        antecedentes(0, 0, 0, 0);
        cuartaParte += ""
                + "                            </div>\n"
                + "                        </div>\n"
                + "                        <div class=\"content\"  id='fem' style='display: none'>\n"
                + "                            <div class=\"divAbsoluto\">\n"
                + "                                <label>Mestruación</label>\n"
                + "                                <select id='mestrua' name='menstruacion' style='width: 40%;color:#666'>\n"
                + "                                    <option value='null' selected name='menstruacion'>Edad primera mestruación</option>\n"
                + "                                    <option value='10'>10 años</option>\n"
                + "                                    <option value='11'>11 años</option>\n"
                + "                                    <option value='12'>12 años</option>\n"
                + "                                    <option value='13'>13 años</option>\n"
                + "                                    <option value='14'>14 años</option>\n"
                + "                                    <option value='15'>15 años</option>\n"
                + "                                    <option value='16'>16 años</option>\n"
                + "                                    <option value='17'>17 años</option>\n"
                + "                                    <option value='0'>No se ha tenido</option>\n"
                + "                                </select>\n"
                + "                            </div>\n"
                + "                            <div class=\"divAbsoluto\">\n"
                + "                                <label>Vida sexual</label>\n"
                + "                                <select id='vidsex' name='vidasexual ' style='width: 40%;color:#666'>\n"
                + "                                    <option value='null' selected name='vidasexual'>Edad de inicio de vida sexual</option>\n"
                + "                                    <option value='1'>1-13 años</option>\n"
                + "                                    <option value='2'>14-18</option>\n"
                + "                                    <option value='3'>19-25</option>\n"
                + "                                    <option value='4'>26-35</option>\n"
                + "                                    <option value='5'>35 en adelante</option>\n"
                + "                                    <option value='0'>Aun no se inicia</option>\n"
                + "                                </select>\n"
                + "                            </div>\n"
                + "                            <div class=\"divAbsoluto\">\n"
                + "                                <label>Uso de DIU</label>\n"
                + "                                <select name='diu' id='diu' style='width: 40%;color:#666'>\n"
                + "                                    <option value='null' selected nsme='diu'>Uso de DIU</option>\n"
                + "                                    <option value='1'>Si</option>\n"
                + "                                    <option value='0'>No</option>\n"
                + "                                </select>\n"
                + "                            </div>\n"
                + "                            <div class=\"divAbsoluto\">\n"
                + "                                <label>Embarazos</label>\n"
                + "                                <select name='embarazos' id='embar' style='width: 40%;color:#666'>\n"
                + "                                    <option value='null' selected name='embarazo'>Número de embarazos</option>\n"
                + "                                    <option value='0'>Ninguno</option>\n"
                + "                                    <option value='1'>1-3</option>\n"
                + "                                    <option value='2'>4 o más</option>\n"
                + "                                </select>\n"
                + "                            </div>\n"
                + "                            <div class=\"divAbsoluto\">\n"
                + "                                <label>Abortos</label>\n"
                + "                                <select name='abortos' id='abort' style='width: 40%;color:#666'>\n"
                + "                                    <option value='null' selected name='abortos'>Número de abortos</option>\n"
                + "                                    <option value='0'>Ninguno</option>\n"
                + "                                    <option value='1'>1-3</option>\n"
                + "                                    <option value='2'>4 o más</option>\n"
                + "                                </select>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                        <div class='content'>\n"
                + "                            <div class='divBotones'>\n"
                + "                                <div class='izquierda'>\n"
                + "                                    <span class='previous rojoso' name='previous'>\n"
                + "                                        Anterior\n"
                + "                                    </span>\n"
                + "                                </div>\n"
                + "                                <div class='derecha'>\n"
                + "                                    <span class='next verdeBotones'  name='next' onclick='verifica(3)'>\n"
                + "                                        Siguiente\n"
                + "                                    </span>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                    </fieldset>";
        quintaParte = "<fieldset>\n"
                + "                        <div class='titulo'>\n"
                + "                            Método de Pago\n"
                + "                        </div>\n"
                + "                        <div class='content'>\n"
                + "                            <div class=\"divLargo\">\n"
                + "                                <label for = 'tarjeta' class='labels'>Número de tarjeta:</label>\n"
                + "                                <input type='text' id='tarjeta' maxlength=\"16\" name='tarjeta' onkeypress='return enteros(event)' />\n"
                + "                            </div>\n"
                + "                            <div class='divLargo'>\n"
                + "                                <label  for = 'nomprop' class='labels'>Nombre del propietario:</label>\n"
                + "                                <input type='text' id='nomprop' name='nomProp' onkeypress='return soloLetras(event)'/>\n"
                + "                            </div>\n"
                + "                            <div class='divAbsoluto'>\n"
                + "                                <label for = 'fven' class='labels'>Fecha de vencimiento :</label>\n"
                + "                                <input type='text' id='fven'  name='fdv' maxlength=\"8\" placeholder='MM/AAAA' pattern='/[\\d]{2} \\/ [\\d]{4}/' />\n"
                + "                            </div>\n"
                + "                            <div class='divAbsoluto'>\n"
                + "                                <label for='ccv' class='labels'>CCV:</label>\n"
                + "                                <input type='password' id='ccv' name='CCV' maxlength=\"3\" placeholder ='Ultimos 3 digitos' onkeypress='return enteros(event)' />\n"
                + "                            </div>\n"
                + "                            <div class='divBotones'>\n"
                + "                                <div class='izquierda'>\n"
                + "                                    <span class='previous rojoso' name='previous'>\n"
                + "                                        Anterior\n"
                + "                                    </span>\n"
                + "                                </div>\n"
                + "                                <div class='derecha'>\n"
                + "                                    <span class='next moradoBotones'   name='next' onclick='verifica(4)'>\n"
                + "                                        Enviar\n"
                + "                                    </span>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                    </fieldset>";
        quintaParte += "     </div>\n"
                + "            </form>\n"
                + "        </div>";
        JS = "";

    }

    private void antecedentes(int opcion, int _idPersona, int _idCampo, int valor) {
        try {
            base.conectar();
            try (PreparedStatement statement = base.getStatement("call sp_Antecedentes(?, ?, ?, ?);")) {
                statement.setInt(1, opcion);
                statement.setInt(2, _idPersona);
                statement.setInt(3, _idCampo);
                statement.setInt(4, valor);
                try (ResultSet res = base.realiza(statement)) {
                    while (res.next()) {
                        cuartaParte += "<div>\n"
                                + "   <input type='checkbox' value='A" + res.getString("idDatoAntecedente") + "'' id='A" + res.getString("idDatoAntecedente") + "' name='antecedentes' >\n"
                                + "   <label for='A" + res.getString("idDatoAntecedente") + "'>" + res.getString("descripcionAntecedente") + "</label>\n"
                                + " </div>\n";
                    }
                }
            }
            base.cierraConexion();
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {
            errores.error(ex, base);
        }
    }

}
